const whaleSrcs = [
    require('./media/scenes/sea/whale/whale01.png').default,
    require('./media/scenes/sea/whale/whale02.png').default,
    require('./media/scenes/sea/whale/whale03.png').default,
    require('./media/scenes/sea/whale/whale04.png').default,
    require('./media/scenes/sea/whale/whale05.png').default,
    require('./media/scenes/sea/whale/whale06.png').default,
    require('./media/scenes/sea/whale/whale07.png').default,
    require('./media/scenes/sea/whale/whale08.png').default,
    require('./media/scenes/sea/whale/whale09.png').default,
    require('./media/scenes/sea/whale/whale10.png').default,
    require('./media/scenes/sea/whale/whale11.png').default,
    require('./media/scenes/sea/whale/whale12.png').default,
    require('./media/scenes/sea/whale/whale13.png').default,
    require('./media/scenes/sea/whale/whale14.png').default,
    require('./media/scenes/sea/whale/whale15.png').default,
    require('./media/scenes/sea/whale/whale16.png').default,
    require('./media/scenes/sea/whale/whale17.png').default,
    require('./media/scenes/sea/whale/whale18.png').default,
    require('./media/scenes/sea/whale/whale19.png').default,
    require('./media/scenes/sea/whale/whale20.png').default,
    require('./media/scenes/sea/whale/whale21.png').default,
    require('./media/scenes/sea/whale/whale22.png').default,
    require('./media/scenes/sea/whale/whale23.png').default,
    require('./media/scenes/sea/whale/whale24.png').default,
    require('./media/scenes/sea/whale/whale25.png').default,
    require('./media/scenes/sea/whale/whale26.png').default,
    require('./media/scenes/sea/whale/whale27.png').default,
    require('./media/scenes/sea/whale/whale28.png').default,
    require('./media/scenes/sea/whale/whale29.png').default,
    require('./media/scenes/sea/whale/whale30.png').default,
    require('./media/scenes/sea/whale/whale31.png').default,
    require('./media/scenes/sea/whale/whale32.png').default,
    require('./media/scenes/sea/whale/whale33.png').default,
    require('./media/scenes/sea/whale/whale34.png').default
];

export { whaleSrcs };